/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekene;
import static Classes.Connect.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Apple
 */
public class Automobiles extends javax.swing.JFrame {

    /**
     * Creates new form automobiles
     */
    public Automobiles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pricetxt5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modeltxt = new javax.swing.JTextField();
        newtxt = new javax.swing.JTextField();
        maketxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        geartxt = new javax.swing.JTextField();
        mileagetxt = new javax.swing.JTextField();
        colortxt = new javax.swing.JTextField();
        stocktxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addImage = new javax.swing.JButton();
        addCarbtn = new javax.swing.JButton();
        viewCar = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pricetxt5.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        pricetxt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pricetxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxt5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1700, 1800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Niagara Engraved", 1, 80)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AUTOMOBILES");

        jLabel9.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price($)");

        pricetxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        pricetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Model");

        modeltxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        modeltxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modeltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeltxtActionPerformed(evt);
            }
        });

        newtxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        newtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtxtActionPerformed(evt);
            }
        });

        maketxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        maketxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maketxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maketxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Car Make");

        jLabel10.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Brand New");

        geartxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        geartxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        geartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geartxtActionPerformed(evt);
            }
        });

        mileagetxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        mileagetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mileagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileagetxtActionPerformed(evt);
            }
        });

        colortxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        colortxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colortxtActionPerformed(evt);
            }
        });

        stocktxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        stocktxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stocktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocktxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gear");

        jLabel4.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Color");

        jLabel11.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mileage");

        jLabel6.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("In Stock");

        addImage.setBackground(new java.awt.Color(255, 255, 255));
        addImage.setFont(new java.awt.Font("Niagara Engraved", 1, 44)); // NOI18N
        addImage.setText("Add Image");
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });

        addCarbtn.setBackground(new java.awt.Color(255, 255, 255));
        addCarbtn.setFont(new java.awt.Font("Niagara Engraved", 1, 44)); // NOI18N
        addCarbtn.setText("Add Car To Shop");
        addCarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarbtnActionPerformed(evt);
            }
        });

        viewCar.setBackground(new java.awt.Color(255, 255, 255));
        viewCar.setFont(new java.awt.Font("Niagara Engraved", 1, 44)); // NOI18N
        viewCar.setText("View All Cars");

        resetbtn.setText("jButton1");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modeltxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maketxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(111, 111, 111)
                                .addComponent(newtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(258, 258, 258)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6))
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mileagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(831, 831, 831)
                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(701, 701, 701))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCarbtn)
                            .addComponent(viewCar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(734, 734, 734))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addImage)
                        .addGap(771, 771, 771))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(modeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maketxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(mileagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(stocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(addImage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(addCarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(viewCar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/car_features.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


   
    private void pricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtActionPerformed

    private void modeltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeltxtActionPerformed

    private void newtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newtxtActionPerformed

    private void maketxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maketxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maketxtActionPerformed

    private void geartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geartxtActionPerformed

    private void pricetxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxt5ActionPerformed

    private void mileagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileagetxtActionPerformed

    private void colortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colortxtActionPerformed

    private void stocktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stocktxtActionPerformed


    private void addCarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarbtnActionPerformed
        // TODO add your handling code here:

    String color = colortxt.getText();
    String gear =geartxt.getText();
    String make =maketxt.getText();
    String mileage =mileagetxt.getText();
    String newTxt =newtxt.getText();
    String price =pricetxt.getText();
    String stock =stocktxt.getText();
    String model =modeltxt.getText();

 
    if(color.isEmpty() || gear.isEmpty()|| make.isEmpty() || mileage.isEmpty() || newTxt.isEmpty() || price.isEmpty() || stock.isEmpty() || model.isEmpty()){  // THIS IF STATEMENT IS TO MAKE SURE THE INPUT FIELDS ARE FILLED
    JOptionPane.showMessageDialog(this, "Fill in the neccessary fields");
    }
    else{
    double prices = Double.parseDouble(price);
    String query = "INSERT INTO carTable(price,model,make,newBrand,gear,color,mileage,inStock) values(?,?,?,?,?,?,?,?) ";
    try{
    ps = getConnection().prepareStatement(query);
    ps.setDouble(1, prices);
    ps.setString(2, model);
    ps.setString(3, make);
    ps.setString(4, newTxt);
    ps.setString(5, gear);
    ps.setString(6, color);
    ps.setString(7, mileage);
    ps.setString(8, stock);
    
    if (ps.executeUpdate() == 1) {
    JOptionPane.showMessageDialog(this, "Car Added Successfully");
    }

    }catch(SQLException ex){
     System.out.println(ex.getMessage());
    }
    }
    
    System.out.print("balls");
    
   

    }//GEN-LAST:event_addCarbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
       colortxt.setText("");
       geartxt.setText("");
       maketxt.setText("");
      mileagetxt.setText("");
      newtxt.setText("");
      pricetxt.setText("");
      stocktxt.setText("");
     modeltxt.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Automobiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarbtn;
    private javax.swing.JButton addImage;
    public static javax.swing.JTextField colortxt;
    public static javax.swing.JTextField geartxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField maketxt;
    public static javax.swing.JTextField mileagetxt;
    public static javax.swing.JTextField modeltxt;
    public static javax.swing.JTextField newtxt;
    public static javax.swing.JTextField pricetxt;
    public static javax.swing.JTextField pricetxt5;
    private javax.swing.JButton resetbtn;
    public static javax.swing.JTextField stocktxt;
    private javax.swing.JButton viewCar;
    // End of variables declaration//GEN-END:variables
}
