/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekene;
import Classes.Cars;
import static Classes.Connect.*;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Apple
 */
public class Automobiles extends javax.swing.JFrame {
    
    int id =1;
    Cars car = new Cars();
    ArrayList<Cars> cars_list = car.carList();
        ArrayList<Cars> img_li = car.carList();
        
    /**
     * Creates new form automobiles
     */
    public Automobiles() {
        initComponents();
        
        addCar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pricetxt5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modeltxt = new javax.swing.JTextField();
        newtxt = new javax.swing.JTextField();
        maketxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        geartxt = new javax.swing.JTextField();
        mileagetxt = new javax.swing.JTextField();
        colortxt = new javax.swing.JTextField();
        stocktxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addImage = new javax.swing.JButton();
        addCarbtn = new javax.swing.JButton();
        viewCar = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pricetxt5.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        pricetxt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pricetxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxt5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1700, 1800));
        setPreferredSize(new java.awt.Dimension(1700, 1800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1603, 1110));

        jLabel8.setFont(new java.awt.Font("Niagara Engraved", 1, 80)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AUTOMOBILES");

        jLabel9.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price($)");

        pricetxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        pricetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Model");

        modeltxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        modeltxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modeltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeltxtActionPerformed(evt);
            }
        });

        newtxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        newtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtxtActionPerformed(evt);
            }
        });

        maketxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        maketxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maketxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maketxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Car Make");

        jLabel10.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Brand New");

        geartxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        geartxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        geartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geartxtActionPerformed(evt);
            }
        });

        mileagetxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        mileagetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mileagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileagetxtActionPerformed(evt);
            }
        });

        colortxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        colortxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colortxtActionPerformed(evt);
            }
        });

        stocktxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        stocktxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stocktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocktxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gear");

        jLabel4.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Color");

        jLabel11.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mileage");

        jLabel6.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("In Stock");

        addImage.setBackground(new java.awt.Color(0, 0, 0));
        addImage.setFont(new java.awt.Font("Niagara Engraved", 1, 44)); // NOI18N
        addImage.setForeground(new java.awt.Color(255, 255, 255));
        addImage.setText("Add Image");
        addImage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });

        addCarbtn.setBackground(new java.awt.Color(0, 0, 0));
        addCarbtn.setFont(new java.awt.Font("Niagara Engraved", 1, 44)); // NOI18N
        addCarbtn.setForeground(new java.awt.Color(255, 255, 255));
        addCarbtn.setText("Add Car To Shop");
        addCarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarbtnActionPerformed(evt);
            }
        });

        viewCar.setBackground(new java.awt.Color(0, 0, 0));
        viewCar.setFont(new java.awt.Font("Niagara Engraved", 1, 44)); // NOI18N
        viewCar.setForeground(new java.awt.Color(255, 255, 255));
        viewCar.setText("View All Cars");
        viewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCarActionPerformed(evt);
            }
        });

        resetbtn.setText("jButton1");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(727, 727, 727))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modeltxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maketxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(111, 111, 111)
                                .addComponent(newtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(viewCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addCarbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6))
                                .addGap(130, 130, 130)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(geartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(colortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mileagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(699, 699, 699)
                        .addComponent(jLabel8)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(addImage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(668, 668, 668))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(modeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maketxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(mileagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(stocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(addImage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(addCarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(viewCar)
                .addGap(45, 45, 45)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/car_features.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1700, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addCarId(int car_id){
    ArrayList <Integer> imgList = Cars.car_id(car_id);
    String [] column = {"Car ID"};
    Object [][] row = new Object[imgList.size()][column.length];
    for(int i = 0; i < imgList.size(); i++){
        row[i][0] = imgList.get(i);
        
        DefaultTableModel model = new DefaultTableModel(row, column);
        Car_Images.idTable.setModel(model);
    }
    }
    
    public void addCar(){
        cars_list = car.carList();
    String [] column = {"Id", "Prices", "Models", "Makes", "Brands", "Gears", "Colors", "Mileages", "Stock"};
    Object [][] row = new Object[cars_list.size()][column.length];
    for(int i = 0; i < cars_list.size(); i++){
        row[i][0] = cars_list.get(i).getId();
        row[i][1] = cars_list.get(i).price();      
        row[i][2] = cars_list.get(i).model();      
        row[i][3] = cars_list.get(i).make();      
        row[i][4] = cars_list.get(i).newBrand();      
        row[i][5] = cars_list.get(i).gear();      
        row[i][6] = cars_list.get(i).color();      
        row[i][7] = cars_list.get(i).mileage();      
        row[i][8] = cars_list.get(i).inStock();      
    }
    
    
    // Create a new table model with the data
    DefaultTableModel model = new DefaultTableModel(row, column);
    
    if (View_Cars.allTableau != null) {
        View_Cars.allTableau.setModel(model);
    } else {
        System.out.println("Table not initialized!");
    }
    }
   
    private void pricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtActionPerformed

    private void modeltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeltxtActionPerformed

    private void newtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newtxtActionPerformed

    private void maketxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maketxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maketxtActionPerformed

    private void geartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geartxtActionPerformed

    private void pricetxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxt5ActionPerformed

    private void mileagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileagetxtActionPerformed

    private void colortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colortxtActionPerformed

    private void stocktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stocktxtActionPerformed

    private void addCarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarbtnActionPerformed
        // TODO add your handling code here:

    String color = colortxt.getText();
    String gear =geartxt.getText();
    String make =maketxt.getText();
    String mileage =mileagetxt.getText();
    String newTxt =newtxt.getText();
    String price =pricetxt.getText();
    String stock =stocktxt.getText();
    String model =modeltxt.getText();

 
    if(color.isEmpty() || gear.isEmpty()|| make.isEmpty() || mileage.isEmpty() || newTxt.isEmpty() || price.isEmpty() || stock.isEmpty() || model.isEmpty()){  // THIS IF STATEMENT IS TO MAKE SURE THE INPUT FIELDS ARE FILLED
    JOptionPane.showMessageDialog(this, "Fill in the neccessary fields");
    }
    else{
    double prices = Double.parseDouble(price);
    String query = "INSERT INTO carTable(price,model,make,newBrand,gear,color,mileage,inStock) values(?,?,?,?,?,?,?,?) ";
    try{
    ps = getConnection().prepareStatement(query);
    ps.setDouble(1, prices);
    ps.setString(2, model);
    ps.setString(3, make);
    ps.setString(4, newTxt);
    ps.setString(5, gear);
    ps.setString(6, color);
    ps.setString(7, mileage);
    ps.setString(8, stock);
    
    if (ps.executeUpdate() == 1) {
    JOptionPane.showMessageDialog(this, "Car Added Successfully");
    }

    }catch(SQLException ex){
     System.out.println(ex.getMessage());
    }
    }
    
    System.out.print("balls");
    
   

    }//GEN-LAST:event_addCarbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
       colortxt.setText("");
       geartxt.setText("");
       maketxt.setText("");
      mileagetxt.setText("");
      newtxt.setText("");
      pricetxt.setText("");
      stocktxt.setText("");
     modeltxt.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        // TODO add your handling code here:
        Car_Images carImg = new Car_Images();
        carImg.setVisible(true);
        this.hide();
        
       String sqlQuery = "SELECT * FROM carTable WHERE id = ? "; // INSERTS A QUERY STATEMENT USING PS WHICH CONVERTS CODE IN THE SQL ENVIROMENT

        try{
            ps = getConnection().prepareStatement(sqlQuery);
            //ps.setInt(1,ider);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            
            if(rs.next()){
            String price = rs.getString("price");
            String model = rs.getString("model");
            String make = rs.getString("make");
            String stock = rs.getString("inStock");
            int ider = rs.getInt("id");
            String ids= Integer.toString(ider);

                JTextField idd = Car_Images.idtxt;
                idd.setText(ids);
                idd.setEditable(false);

                JTextField models = Car_Images.modeltxt;
                models.setText(model);
                models.setEditable(false);

                JTextField makes = Car_Images.maketxt;
                makes.setText(make);
                makes.setEditable(false);

                JTextField pricey = Car_Images.pricetxt;
                pricey.setText(price);
                pricey.setEditable(false);
                
                addCarId(ider);
                

            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
       JLabel images = Car_Images.image;
       
       /*
        String path = "C:\\Users\\Apple\\Documents\\NetBeansProject\\Ekene&SonsAutos\\src\\Images\\car_plans";
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(images.getWidth(), images.getHeight(), Image.SCALE_SMOOTH);// This resizes the image
        Car_Images.image.setIcon( new ImageIcon(img));
    */
    }//GEN-LAST:event_addImageActionPerformed

    private void viewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCarActionPerformed
        // TODO add your handling code here:
        View_Cars view = new View_Cars();
        view.setVisible(true);
        this.hide();
        addCar();
    }//GEN-LAST:event_viewCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Automobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Automobiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarbtn;
    private javax.swing.JButton addImage;
    public static javax.swing.JTextField colortxt;
    public static javax.swing.JTextField geartxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField maketxt;
    public static javax.swing.JTextField mileagetxt;
    public static javax.swing.JTextField modeltxt;
    public static javax.swing.JTextField newtxt;
    public static javax.swing.JTextField pricetxt;
    public static javax.swing.JTextField pricetxt5;
    private javax.swing.JButton resetbtn;
    public static javax.swing.JTextField stocktxt;
    private javax.swing.JButton viewCar;
    // End of variables declaration//GEN-END:variables
}
