/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekene;
import static Classes.Connect.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Apple
 */
public class Userinfo extends javax.swing.JFrame {

    /**
     * Creates new form userinfo
     */
    public Userinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userProfile = new javax.swing.JButton();
        wallet = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        userProfile.setBackground(new java.awt.Color(0, 0, 0));
        userProfile.setFont(new java.awt.Font("Niagara Engraved", 1, 40)); // NOI18N
        userProfile.setForeground(new java.awt.Color(255, 255, 255));
        userProfile.setText("UserInfo");
        userProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileActionPerformed(evt);
            }
        });

        wallet.setBackground(new java.awt.Color(0, 0, 0));
        wallet.setFont(new java.awt.Font("Niagara Engraved", 1, 40)); // NOI18N
        wallet.setForeground(new java.awt.Color(255, 255, 255));
        wallet.setText("Wallet");
        wallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletActionPerformed(evt);
            }
        });

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setFont(new java.awt.Font("Niagara Engraved", 1, 40)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Niagara Engraved", 1, 70)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("User Sub-Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(wallet, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileActionPerformed
        // TODO add your handling code here:
        Users user = new Users();
        user.setVisible(true);
        this.hide();

        // THIS IS TO SET THE VARIABLES IN THE REGISTRATION FORM
        String query = "SELECT * FROM userTable WHERE userName = ? "; // INSERTS A QUERY STATEMENT USING PS WHICH CONVERTS CODE IN THE SQL ENVIROMENT

        String usernamer = Ekene_SonsAutos.usernametxt.getText();
        // PS CONVERTS CODE IN THE SQL ENVIROMENT AND THIS SETS THE JFIELDS INTO THE SQL
        try{
            ps = getConnection().prepareStatement(query);
            ps.setString(1, usernamer);
            rs = ps.executeQuery();
            if(rs.next()){
                String fullName = rs.getString("fullName");
                String plan = rs.getString("plan");
                String email = rs.getString("email");
                String pass = rs.getString("pass");
                String username = rs.getString("userName");
                String discount = rs.getString("discount");

                System.out.println("balls");

                JTextField fullnametxt = Users.fullnametxt;
                fullnametxt.setText(fullName);
                fullnametxt.setEditable(false);
                JTextField plantxt = Users.planstxt;
                plantxt.setText(plan);
                plantxt.setEditable(false);
                JTextField userName = Users.userNametxt;
                userName.setText(username);
                userName.setEditable(false);
                JTextField dis= Users.discounttxt;
                dis.setText(discount);
                dis.setEditable(false);
                JTextField mail = Users.emailtxt;
                mail.setText(email);
                mail.setEditable(false);

            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_userProfileActionPerformed

    private void walletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletActionPerformed
        // TODO add your handling code here:
        String query = "SELECT * FROM userTable WHERE userName = ? "; // INSERTS A QUERY STATEMENT USING PS WHICH CONVERTS CODE IN THE SQL ENVIROMENT

        String usernamer = Ekene_SonsAutos.usernametxt.getText();
        double balance = 0;
        // PS CONVERTS CODE IN THE SQL ENVIROMENT AND THIS SETS THE JFIELDS INTO THE SQL
        try{
            ps = getConnection().prepareStatement(query);
            ps.setString(1, usernamer);
            rs = ps.executeQuery();

            if(rs.next()){
                balance = rs.getDouble("deposit");;
            }  
            } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        Wallet wall = new Wallet();
        wall.setWallet(balance);
        wall.setVisible(true);
        this.hide();  
    }//GEN-LAST:event_walletActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
       this.hide();
       m.setVisible(true); 
        
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton menu;
    public static javax.swing.JButton userProfile;
    public static javax.swing.JButton wallet;
    // End of variables declaration//GEN-END:variables
}
