/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekene;

import static Classes.Connect.getConnection;
import static Classes.Connect.ps;
import static Classes.Connect.rs;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Apple
 */
public class Wallet extends javax.swing.JFrame {
        double wallet;
    /**
     * Creates new form Wallet
     */
    public Wallet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        balancetxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        deposittxt = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        buybtn = new javax.swing.JButton();
        added = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Niagara Engraved", 1, 90)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("WALLET");

        balancetxt.setFont(new java.awt.Font("Niagara Engraved", 1, 35)); // NOI18N
        balancetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        balancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancetxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel13.setText("Balance ($)");

        deposittxt.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        deposittxt.setForeground(new java.awt.Color(153, 102, 0));
        deposittxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10000", "50000", "80000", "100000", "500000", "800000", "1000000", " ", " ", " ", " ", " ", " " }));

        jLabel14.setFont(new java.awt.Font("Niagara Engraved", 1, 50)); // NOI18N
        jLabel14.setText("Deposit ($)");

        buybtn.setBackground(new java.awt.Color(0, 0, 0));
        buybtn.setFont(new java.awt.Font("Niagara Engraved", 1, 40)); // NOI18N
        buybtn.setForeground(new java.awt.Color(255, 255, 255));
        buybtn.setText("Deposit");
        buybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buybtnActionPerformed(evt);
            }
        });

        added.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        added.setForeground(new java.awt.Color(204, 204, 255));
        added.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(466, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deposittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(balancetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(added, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buybtn)
                        .addGap(677, 677, 677))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(602, 602, 602))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(balancetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(added))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deposittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120)
                .addComponent(buybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setWallet(double balance){
        String balances = Double.toString(balance);
        balancetxt.setText(balances);
        balancetxt.setEditable(false);
        this.wallet = balance;
    }
    
    public double getWallets(){
        return wallet;
    }
    
    private void balancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balancetxtActionPerformed

    private void buybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buybtnActionPerformed
        // TODO add your handling code here:

        String query = "SELECT * FROM userTable WHERE userName = ? ";
        double deposit = 0;
        String usernamer = Ekene_SonsAutos.usernametxt.getText();

        try{
            ps = getConnection().prepareStatement(query);
            ps.setString(1, usernamer);
            rs = ps.executeQuery();

            if(rs.next()){
                deposit = rs.getDouble("deposit");
                Payment pay = new Payment();

                double get_wallet = getWallets();
                System.out.println(getWallets());
                
               String depositer =  (String) deposittxt.getSelectedItem();
               double deposit_cash = Double.parseDouble(depositer);

                if(!(deposit_cash == 0)){
                    JOptionPane.showMessageDialog(this, "Money Has Been Added To Wallet");

                    String n_query = "update userTable set deposit = ? where userName = ?";
                    String username = Ekene_SonsAutos.usernametxt.getText();

                    try{
                        ps = getConnection().prepareStatement(n_query);
                        double get_balance =  get_wallet + deposit_cash ;
                        ps.setDouble(1, get_balance);
                        ps.setString(2, username);

                        int rowsAffected = ps.executeUpdate();
                        if (rowsAffected > 0) {
                            
                            System.out.println("User Wallet updated successfully.");
                            String new_query = "SELECT * FROM userTable WHERE userName = ? "; 

                            String user = Ekene_SonsAutos.usernametxt.getText();
                            double balance = 0;
                            try{
                                ps = getConnection().prepareStatement(new_query);
                                ps.setString(1, user);
                                rs = ps.executeQuery();

                                if(rs.next()){
                                    balance = rs.getDouble("deposit");;
                                }  
                                } catch (SQLException ex) {
                                System.out.println(ex.getMessage());
                            }

                                Wallet wall = new Wallet();
                                wall.setWallet(balance);
                                wall.added.setText("new");
                                wall.setVisible(true);
                                this.hide();                
                            } else {
                                System.out.println("User not found or no rows affected.");
                            }
                    }
                    catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
                }
                else {
                    JOptionPane.showMessageDialog(this, "No Funds To Add");

                }
            }}
            catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
    }//GEN-LAST:event_buybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wallet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel added;
    public static javax.swing.JTextField balancetxt;
    private javax.swing.JButton buybtn;
    private javax.swing.JComboBox<String> deposittxt;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
